apiVersion: v1
kind: PersistentVolume
metadata:
        name: postgres-pv-volume-client
        labels:
                type: local
spec:
        storageClassName: manual
        capacity:
                storage: 5Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: "/mnt/data"
